language: scala

scala:
  - 2.11.11

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi; "
    
script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION 'release with-defaults'; else sbt ++$TRAVIS_SCALA_VERSION test coverageReport coverageAggregate; fi"

after_success:
  - find \$HOME/.sbt -name "*.lock" | xargs rm
  - find \$HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - "bash <(curl -s https://codecov.oncue.verizon.net/bash) -u https://codecov.oncue.verizon.net -r $TRAVIS_REPO_SLUG -t ee377c2d-25fd-4755-a144-887166d1b0d6"

cache:
  directories:
    - \$HOME/.ivy2/cache
    - \$HOME/.sbt/boot/scala-\$TRAVIS_SCALA_VERSION

notifications:
   email:
     recipients:
       - dustin.withers@one.verizon.com
     on_success: change
     on_failure: always
